### ISSUE TITLE
Frontend Open-sourced?

### ISSUE THREAD

**Issue by kumkee** [alpaca-finance/bsc-alpaca-contract#144]
Is your Frontend Webpage open-sourced?
If so, where does its code locate?
If not, can you open it please?
I am a leveraged farmer on your platform trying to write a programme to tract the safety buffers of my vaults. Then I guessed your frontend would be the perfect place to start.

**Comment by nguyenhoangsin** [comment]
I think that is the best dream :))

**Comment by kumkee** [comment]
> I think that is the best dream :))

At least it is not a daydream as Pancakeswap has [theirs open-sourced](https://github.com/pancakeswap/pancake-frontend).

**Comment by ricardo-alpaca** [comment]
We do not open-source our frontend. This due to security concerns of site phishing and other possible vulnerabilities.
If you would like any details of the calculation on our site, you could study from our contract codes, our docs or reach out to us in our Discord.

Docs: https://docs.alpacafinance.org/
Discord: https://discord.com/invite/2UvgmqcVDQ

**Comment by kumkee** [comment]
> We do not open-source our frontend. This due to security concerns of site phishing and other possible vulnerabilities.
> If you would like any details of the calculation on our site, you could study from our contract codes, our docs or reach out to us in our Discord.
> 
> Docs: https://docs.alpacafinance.org/
> Discord: https://discord.com/invite/2UvgmqcVDQ

Fair enough. I appreciate that.
Could you please just answer one technical question here please?
Knowing the wallet address, which contract do I call to get a list of my vault position numbers?
